version: "3.8"

services:
  web:
    build: .
    command: ["./entrypoint.sh"]
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
