version: "3.8"

services:
  web:
    build: .
    command: bash -c "poetry run uvicorn cid.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - .:/code
    ports:
      - 8000:80
    environment:
      ENVIRONMENT: production
    depends_on:
      - db

  db:
    image: docker.io/library/postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
